p,b=len(y:=[list(l.strip()) for l in open('i','r')]),len(y[0])
f=lambda i,j,k,l,x:0<=i<p and 0<=j<b and(x[i][j]=="#"or(x[i][j]=="."and f(i+k,j+l,k,l,x)))
d=lambda i,j,y:sum(f(i+k,j+l,k,l,y)for k in[-1,0,1]for l in[-1,0,1]if(k,l)!=(0,0))
m=lambda i,j,x:"#"if x[i][j]=="L"and d(i,j,x)==0 else("L"if x[i][j]=="#"and d(i,j,x)>4 else x[i][j])
e=lambda x:k if x==(k:=[[m(i,j,x)for j in range(b)]for i in range(p)])else e(k)
print(sum(c=="#"for l in e(y) for c in l))